title: Awesome Cognitive Metascience List
description: An Overview of Essential Resources for the Study of Cognitive Metascience
theme: minima

markdown: CommonMarkGhPages

header_pages:
  - README.md
