title: Awesome Cognitive Metascience List
description: An Overview of Essential Resources for the Study of Cognitive Metascience
theme: jekyll-theme-cayman

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block: true

header_pages:
  - README.md
